import { chromium } from "playwright";
const BASE = "http://localhost:5173";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(BASE + "/", { waitUntil: "networkidle" });
await page.getByTestId("login-button").click();
await page.waitForURL("**/board", { timeout: 10000 });
await page.waitForTimeout(400);
console.log("theme antes:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
await page.getByRole("button", { name: "Alternar tema" }).click();
await page.waitForTimeout(300);
console.log("theme após:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
console.log("localStorage:", await page.evaluate(() => localStorage.getItem("kbd-theme")));
await page.evaluate(() => { document.documentElement.setAttribute("data-theme","dark"); });
await page.waitForTimeout(300);
await page.screenshot({ path: "/root/workspace/kanban-dev-app/e2e/board-dark.png", fullPage: true });
console.log("forçado dark e capturado");
await browser.close();
