import { chromium } from "playwright";
const BASE = "http://localhost:5173";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
await page.getByTestId("login-button").waitFor({ timeout: 10000 });
await page.getByTestId("login-button").click();
await page.waitForURL("**/board", { timeout: 10000 });
await page.waitForTimeout(600);
const btn = page.getByRole("button", { name: "Alternar tema" });
const t0 = await page.evaluate(() => document.documentElement.getAttribute("data-theme"));
await btn.click();
await page.waitForTimeout(300);
const t1 = await page.evaluate(() => document.documentElement.getAttribute("data-theme"));
console.log(`inicial=${t0} após1clique=${t1}`);
await browser.close();
