// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Column struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Position int32  `json:"position"`
}

type Task struct {
	ID          int32     `json:"id"`
	ColumnID    int32     `json:"column_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
